insert into USER_DETAILS(DOB,ID,NAME) values (CURRENT_DATE,1001,'Anuma');
insert into USER_DETAILS(DOB,ID,NAME) values (CURRENT_DATE,1002,'Ajith');
insert into USER_DETAILS(DOB,ID,NAME) values (CURRENT_DATE,1003,'Abhi');
insert into USER_DETAILS(DOB,ID,NAME) values (CURRENT_DATE,1004,'Raju');
insert into USER_DETAILS(DOB,ID,NAME) values (CURRENT_DATE,1005,'KAju');
insert into POST(ID,USER_ID, DESCRIPTION) values (1,1001,'I am a Certified AWS Associate Solution Architect');
insert into POST(ID,USER_ID, DESCRIPTION) values (2,1001,'I am going to be a Certified Java Developer');
insert into POST(ID,USER_ID, DESCRIPTION) values (3,1003,'I am a sleeper ');
insert into POST(ID,USER_ID, DESCRIPTION) values (4,1002,'I am a Certified Sleeper');
insert into POST(ID,USER_ID, DESCRIPTION) values (5,1003,'I am a Certified Hero');